<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="LAPTOP-CKOV7N0K" name="com.auz.selenium.ui.candidate.testcases.AddCandidate" tests="1" failures="0" timestamp="2020-05-22T11:56:08 IST" time="58.597" errors="1">
  <testcase name="TC001_verify_user_is_able_to_add_candidate_successfully_without_mapping_job" time="58.597" classname="com.auz.selenium.ui.candidate.testcases.AddCandidate">
    <error type="java.lang.RuntimeException" message="Server returned HTTP response code: 401 for URL: https://auzmorhr.testrail.io/index.php?/api/v2/add_result/258346">
      <![CDATA[java.lang.RuntimeException: Server returned HTTP response code: 401 for URL: https://auzmorhr.testrail.io/index.php?/api/v2/add_result/258346
at com.auz.selenium.CoreUtils.SeleniumBase.sendPostRequest(SeleniumBase.java:650)
at com.auz.selenium.CoreUtils.SeleniumBase.updateTestRailResultAsFail(SeleniumBase.java:623)
at com.auz.selenium.ui.candidate.testcases.AddCandidate.TC001_verify_user_is_able_to_add_candidate_successfully_without_mapping_job(AddCandidate.java:68)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TC001_verify_user_is_able_to_add_candidate_successfully_without_mapping_job -->
  <system-out/>
</testsuite> <!-- com.auz.selenium.ui.candidate.testcases.AddCandidate -->
